# Generated by Django 6.0.6 on 2026-06-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthotizedUsers',
            new_name='AuthorizedUsers',
        ),
    ]
